name: Update data
on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run update
        run: export NEW_DATE=$(python ci/update_ll_points.py)
      - if: ${{ env.NEW_DATE != '' }}
        name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update data following $NEW_DATE changes
          file_pattern: '*.csv'

